BYTE-158: Styling Promobar Countdown Timer
astrogoat/promobar pull request #4
Opened 2023-07-21 10:17 UTC by iamkarsoft

**Link to ticket**: https://linear.app/3zbrands/issue/BYTE-158/styling

<details>
<summary>Ticket description</summary>
As a user looking at the promobar when the countdown timer is enabled, I want to see the countdown timer sitting between the copy and the View Offer link (if it exists) so that I know how much time remains until the sale ends.
</details>

2023-07-21 12:11 UTC, BaffourAdu approved these changes

2023-07-21 12:14 UTC, OniiCoder approved these changes

2023-07-24 12:26 UTC, tonning requested changes

2023-07-24 12:26 UTC, tonning commented on resources/views/components/countdown.blade.php
Hi Kofi, unfortunately we can't rely on Tailwind classes always being available to us here, only if the site the promobar is used on also has generated that class because it needs it somewhere else will it be available. So we need to explicitly define them to be on the safe site.
The easiest way is likely to copy the CSS that Tailwind generates for each of the used classes and add as inline styles.

2023-07-26 15:04 UTC, nrthbound approved these changes

2023-07-28 10:47 UTC, tonning approved these changes

2023-07-28 10:47 UTC, merged